remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

title: Комп'ютерні науки
name: VVKo
email: your-email@example.com
description: Публічна документація
baseurl: "/" # the subpath of your site, e.g. /blog
#url: https://nat-dep-clg.github.io # the base hostname & protocol for your site, e.g. http://example.com
url: https://nat-dep-clg-chnu-cs/nat-dep-clg-chnu-cs.github.io
#repository: "nat-dep-clg/CS"
repository: "nat-dep-clg-chnu-cs/nat-dep-clg-chnu-cs.github.io"
github_username: nat-dep-clg-chnu
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
plugins:
  - jekyll-include-cache
  - jekyll-feed

include:
  - _pages
